import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenu from "@/components/sidemenu/SideMenu";
import Header from "@/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        {/* Header */}
        <Header />

        <div className="flex lg:ml-[270px] order-1 h-screen">
          {/* Sidebar */}
         
            <SideMenu />
        

          {/* Main Content */}
          <main className="flex-1 mt-20 md:p-6 overflow-y-auto bg-gray-200 shadow-md">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
